# Generated by Django 4.1.5 on 2023-01-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_question_follow_up_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='filledquestionair',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='qustionanswer',
            name='answer_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='filledquestionair',
            name='questionair_id',
            field=models.IntegerField(unique=True),
        ),
    ]
