# Generated by Django 4.1.5 on 2023-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_rename_pass_choise_choice_pass_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='follow_up_answer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
