# Generated by Django 4.1.5 on 2023-01-20 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledQuestionair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_code', models.CharField(max_length=6)),
                ('month_of_birth', models.IntegerField()),
                ('year_of_birth', models.IntegerField()),
                ('questionair_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_code', models.CharField(max_length=20)),
                ('text_pl', models.CharField(max_length=2000)),
                ('text_en', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choice_text_pl',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_text_en',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='form_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('FOLLOW-UP', 'Follow-up')], default='Basic', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='pass_choise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_pl',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QustionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_answer', models.CharField(max_length=2000)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question')),
                ('quistionair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.filledquestionair')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.question')),
            ],
        ),
    ]
