# Generated by Django 4.1.5 on 2023-01-26 09:11

from django.db import migrations

def insert_questionaire(apps, schema_editor):

    questionModel = apps.get_model('polls', 'Question')
    question = question.
    questionModel.objects.create(
        
    )

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_filledquestionair_webtext_and_more'),
    ]

    operations = [
    ]
