# Generated by Django 4.1.5 on 2023-01-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_filledquestionair_webtext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text_en',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='follow_up_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.choice'),
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='question_follow_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_follow_up_id', to='polls.question'),
        ),
    ]
